# Auto-generated by rebuild_inits.py — do not hand-edit.
# Re-exports selected public symbols lazily to preserve import time.
from importlib import import_module as _im
from typing import Any as _Any

__all__ = [
    'GoogleOAuthService',
    'OAuthError',
    'TokenInfo',
    'TokenStore',
    'get_api_token_store',
    'get_cli_token_store',
    'get_system_username',
    'oauth_service',
    'token_store'
]

# map symbol -> relative module
_symbol_map = {'OAuthError': 'oauth_service', 'GoogleOAuthService': 'oauth_service', 'get_api_token_store': 'token_store', 'TokenStore': 'token_store', 'TokenInfo': 'token_store', 'get_system_username': 'token_store', 'get_cli_token_store': 'token_store'}
_module_map = {'oauth_service': 'oauth_service', 'token_store': 'token_store'}


def __getattr__(name: str) -> _Any:  # PEP 562
    mod = _symbol_map.get(name)
    if mod is not None:
        module = _im(f".{mod}", __name__)
        return getattr(module, name)

    pkg = _module_map.get(name)
    if pkg is not None:
        return _im(f".{pkg}", __name__)

    raise AttributeError(f"module {__name__} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals().keys()) | set(__all__))
